// react-ui/src/components/Auth/Register.js
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import './Auth.css';

const Register = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    username: '',
    password: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  const { register } = useAuth();
  const navigate = useNavigate();

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    const result = await register(
      formData.name,
      formData.email,
      formData.username,
      formData.password
    );

    if (result.success) {
      setSuccess(true);
      setTimeout(() => {
        navigate('/login');
      }, 2000);
    } else {
      setError(result.error);
    }

    setLoading(false);
  };

  return (
    <div className="auth-container">
      <div className="auth-card">
        <h2>Register</h2>

        {error && (
          <div className="alert alert-error">
            {error}
          </div>
        )}

        {success && (
          <div className="alert alert-success">
            Registration successful! Redirecting to login...
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="name">Full Name</label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
              placeholder="Enter your name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              required
              placeholder="Enter email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="username">Username</label>
            <input
              type="text"
              id="username"
              name="username"
              value={formData.username}
              onChange={handleChange}
              required
              minLength="3"
              placeholder="Choose a username"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              required
              minLength="6"
              placeholder="Choose a password (min 6 characters)"
            />
          </div>

          <button type="submit" className="btn btn-primary btn-block" disabled={loading}>
            {loading ? 'Registering...' : 'Register'}
          </button>

          <div className="auth-link">
            <p>Already have an account? <Link to="/login">Login here</Link></p>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Register;

// angular-ui/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  registerForm: FormGroup;
  loading = false;
  error = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    // Redirect if already logged in
    if (this.authService.isLoggedIn()) {
      this.router.navigate(['/todos']);
    }

    this.registerForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      username: ['', [Validators.required, Validators.minLength(3)]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  get f() {
    return this.registerForm.controls;
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = '';

    this.authService.register(this.registerForm.value).subscribe({
      next: () => {
        this.router.navigate(['/todos']);
      },
      error: (err) => {
        this.error = err.error?.message || 'Registration failed. Please try again.';
        this.loading = false;
      }
    });
  }

  goToLogin(): void {
    this.router.navigate(['/login']);
  }
}

<div class="register-container">
    <div class="register-card">
        <div class="register-header">
            <h1>📝 Todo App</h1>
            <h2>Create Account</h2>
        </div>

        <div *ngIf="error" class="alert alert-error">
            {{ error }}
        </div>

        <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="name">Full Name</label>
                <input
                        id="name"
                        type="text"
                        formControlName="name"
                        class="form-control"
                        [class.is-invalid]="f['name'].touched && f['name'].errors"
                        placeholder="Enter your full name"
                        autofocus
                />
                <div *ngIf="f['name'].touched && f['name'].errors" class="invalid-feedback">
                    Name is required
                </div>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input
                        id="email"
                        type="email"
                        formControlName="email"
                        class="form-control"
                        [class.is-invalid]="f['email'].touched && f['email'].errors"
                        placeholder="Enter your email"
                />
                <div *ngIf="f['email'].touched && f['email'].errors" class="invalid-feedback">
                    <div *ngIf="f['email'].errors['required']">Email is required</div>
                    <div *ngIf="f['email'].errors['email']">Email must be valid</div>
                </div>
            </div>

            <div class="form-group">
                <label for="username">Username</label>
                <input
                        id="username"
                        type="text"
                        formControlName="username"
                        class="form-control"
                        [class.is-invalid]="f['username'].touched && f['username'].errors"
                        placeholder="Choose a username"
                />
                <div *ngIf="f['username'].touched && f['username'].errors" class="invalid-feedback">
                    <div *ngIf="f['username'].errors['required']">Username is required</div>
                    <div *ngIf="f['username'].errors['minlength']">Username must be at least 3 characters</div>
                </div>
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input
                        id="password"
                        type="password"
                        formControlName="password"
                        class="form-control"
                        [class.is-invalid]="f['password'].touched && f['password'].errors"
                        placeholder="Create a password"
                />
                <div *ngIf="f['password'].touched && f['password'].errors" class="invalid-feedback">
                    <div *ngIf="f['password'].errors['required']">Password is required</div>
                    <div *ngIf="f['password'].errors['minlength']">Password must be at least 6 characters</div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary btn-block" [disabled]="loading">
                {{ loading ? 'Creating account...' : 'Register' }}
            </button>
        </form>

        <div class="register-footer">
            <p>Already have an account? <a (click)="goToLogin()" class="link">Sign in</a></p>
        </div>
    </div>
</div>
